### ISSUE TITLE
License

### ISSUE THREAD

**Issue by petersondrew** [dprotaso/Google.PhoneNumbers#5]
I noticed that while the Apache license is retained on the Google.PhoneNumbers project, you haven't specified a license for the code that you've contributed (e.g. the GenerateData project).

Would you be willing to add a license to this repo to cover the code you've written so that others may work on it as well?

Thank you!

**Comment by dprotaso** [comment]
https://github.com/dprotaso/Google.PhoneNumbers/blob/master/LICENSE

Done - included the Apache 2 license at the top level

**Comment by petersondrew** [comment]
Thank you!
